name: vdss
channels:
  - conda-forge
  - bokeh
dependencies:
  - bokeh=3.6.2
  - cartopy
  - geopandas
  - geoplot
  - geopy
  - ipywidgets
  - jupyterlab=4.3.5
  - jupyter_bokeh
  - mapclassify
  - matplotlib=3.10.0
  - networkx
  - numpy
  - openpyxl
  - pandas=2.2.3
  - pip
  - plotly=5.18.0
  - python=3.10
  - seaborn=0.13.2
  - squarify=0.4.3
  - statsmodels=0.14.4
  - tabulate=0.9.0
  - pip:
      - python-dotenv==1.0.1
      - sankeyflow==0.4.1
      - streamlit==1.42.0
      - matplotlib-venn==1.1.1
      - ydata-profiling==4.12.2
